application: dfmo-group
version: dynamic
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /images
  static_dir: images

- url: /PIE.htc
  static_files: PIE.htc
  upload: PIE.htc
  mime_type: text/x-component

- url: /favicon.png
  static_files: favicon.png
  upload: favicon.png

- url: /.*
  script: main_handler.py

- url: /admin/.*
  script: main_handler.py
  login: admin
